### ISSUE TITLE
KP wrong button.

### ISSUE THREAD

**Issue by judenkirobotics** [judenkirobotics/season2016-17#1]
20160121.01. Severe.  -60 pts.  Bedford.  Wrong button pressed both auto red and auto blue. Possibly much brighter in gym than lab, so hue saturation suspect. Looks like it read blue as red.  Also maybe look at positive hue for blue vs red.

**Comment by 50N40W** [comment]
Added shroud around color sensor (build team)
Added delay for color saturation (Jim)
